export const
    FETCH_QUIZES_START = 'FETCH_QUIZES_START',
    FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS',
    FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR',
    FETCH_QUIZ_ONE_SUCCESS = 'FETCH_QUIZ_ONE_SUCCESS';

export const
    QUIZ_SET_STATE = 'QUIZ_SET_STATE',
    FINISH_QUIZ = 'FINISH_QUIZ',
    QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION',
    RETRY_QUIZ = 'RETRY_QUIZ';

export  const
    FINISH_CREATE_QUIZ = 'FINISH_CREATE_QUIZ',
    CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION';

export const
    AUTH_SUCCESS = 'AUTH_SUCCESS',
    AUTH_LOGOUT = 'AUTH_LOGOUT',
    AUTO_LOGIN = 'AUTO_LOGIN';